all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      become: true
      branch: "main"
      artifact_s3_bucket: "s3://pillow-rke2-ami-ec2ib-pipeline-storage-{{ branch }}"
      cdk_stack_base_name: "MCRIT-RKE2"
      rhel9STIG_stigrule_257970_Manage: False # Possibly needed for containers
      rhel9STIG_stigrule_258090_Manage: False # No Fapolicyd
      rhel9STIG_stigrule_272488_Manage: False # No mailserver (postfix)
      rhel9STIG_stigrule_258036_Manage: False # no usbguard
      rhel9STIG_stigrule_258035_Manage: False # no usbguard
      rhel9STIG_stigrule_257832_Manage: False # IPA Dependency (gssproxy)
      rhel9STIG_stigrule_257849_Manage: False # Autofs
      rhel9STIG_stigrule_257828_Manage: False # NFS Utils
      rhel9STIG_stigrule_257936_Manage: False # Turn off firewalld
      rhel9STIG_stigrule_257949_Manage: False # Breaks Cloud DNS
      loadbalancer_ip: "LOADBALANCER_HERE" # I don't know how we are going to do this one yet.
      cloudwatch_log_rention_days: 60
      rke2_join_token: "eef02a9e-548e-11f0-8faa-f02f740036b7"
      cloudwatch_tracked_logs:
        - {log_path: "/var/log/messages", log_name: "{{ cdk_stack_base_name }}-var-log-messages"}
        - {log_path: "/var/log/secure", log_name: "{{ cdk_stack_base_name }}-var-log-secure"}
        - {log_path: "/var/log/audit/audit.log", log_name: "{{ cdk_stack_base_name }}-var-log-audit"}